# Generated by Django 3.1 on 2020-08-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=128)),
                ('document_type', models.CharField(max_length=32)),
                ('contents', models.TextField()),
                ('icon', models.ImageField(upload_to='icons')),
                ('last_updated', models.TimeField(auto_now=True)),
                ('created', models.TimeField()),
                ('visibility', models.IntegerField(choices=[(1, 'Public'), (2, 'Protected'), (3, 'Private')])),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=32)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.document')),
            ],
        ),
    ]
