# Generated by Django 3.1 on 2020-08-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200819_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contents',
            field=models.IntegerField(choices=[(1, 'Project'), (2, 'Education'), (3, 'Award'), (4, 'Experience')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
