# Generated by Django 3.1 on 2020-08-27 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200824_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='PortfolioAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
    ]
