# Generated by Django 3.1 on 2020-08-27 20:55

from django.db import migrations
from uuid import uuid1

def migrate(apps, schema_editor):
    Portfolio = apps.get_model('portfolio', 'Portfolio')
    for p in Portfolio.objects.all():
        p.uuid = uuid1()
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200827_1655'),
    ]

    operations = [
        migrations.RunPython(migrate, migrations.RunPython.noop)
    ]
