# Generated by Django 3.1 on 2020-08-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200819_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.IntegerField(choices=[(1, 'Project'), (2, 'Education'), (3, 'Award'), (4, 'Experience')]),
        ),
    ]
