# Generated by Django 3.1 on 2020-08-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200819_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(to='portfolio.Tag'),
        ),
        migrations.AlterField(
            model_name='document',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/icons'),
        ),
    ]
