# Generated by Django 3.1 on 2020-08-27 20:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200827_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
